// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXEGUHzMQHzGIPu4NbTzF3-FstaY0b7sI',
    appId: '1:461459370717:web:fafe973dcdfc700087e134',
    messagingSenderId: '461459370717',
    projectId: 'apipython-claseleng',
    authDomain: 'apipython-claseleng.firebaseapp.com',
    databaseURL: 'https://apipython-claseleng-default-rtdb.firebaseio.com',
    storageBucket: 'apipython-claseleng.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATD8B0rz_zMW1hbUqBzK9u72XgKuUKJ6E',
    appId: '1:461459370717:android:5eac3f6ae35e85ca87e134',
    messagingSenderId: '461459370717',
    projectId: 'apipython-claseleng',
    databaseURL: 'https://apipython-claseleng-default-rtdb.firebaseio.com',
    storageBucket: 'apipython-claseleng.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBap9EhR_VmWfsGICBK5bB3vXaAYE7-zxQ',
    appId: '1:461459370717:ios:fe7529d0cb88335687e134',
    messagingSenderId: '461459370717',
    projectId: 'apipython-claseleng',
    databaseURL: 'https://apipython-claseleng-default-rtdb.firebaseio.com',
    storageBucket: 'apipython-claseleng.appspot.com',
    iosClientId: '461459370717-1mialmir6o7pbui3lsmo9ne0k3gc6lav.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupNamer',
  );
}
